Repository prgrms-be-devcourse/NBE6-8-2-Team11, pull requests merged in 2025-08, with the labels that each got.

#91 feat(cd): render 백엔드 배포 설정 완료 및 최신화
  backend/Dockerfile.railway
  frontend/next.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/tailwind.config.js
Labels: deploy

#94 fix(cd,fe): tailwind css를 v3로 다운그레이드
  frontend/next.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/app/globals.css
  frontend/tailwind.config.js
Labels: refactor

#100 feat(cd,fe,be) : cd 자동화 전 에러 안정화
  frontend/src/app/contact/page.tsx
  frontend/src/app/faq/page.tsx
  frontend/src/app/help/page.tsx
  frontend/src/shared/lib/websocket.ts
Labels: deploy

#108 feat(cd): ci/cd 추가 자동화를 위한 워크플로어 설정 그리고 풀스텍 개발
  .github/workflows/backend-deploy.yml
  .github/workflows/frontend-deploy.yml
  .github/workflows/full-stack-deploy.yml
  .github/workflows/pr-notification.yml
  .github/workflows/push-to-fork.yml
  .github/workflows/sync-fork.yml
Labels: deploy

#110 fix(cd): 배포 버그 날 수 있는 부분 수정
  .github/workflows/backend-deploy.yml
  .github/workflows/cd-release.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/frontend-deploy.yml
  .github/workflows/full-stack-deploy.yml
  .github/workflows/push-to-fork.yml
Labels: deploy

#112 fix(ci): 슬랙 알림 수정
  .github/workflows/ci.yml
  .github/workflows/pr-notification-simple.yml
  .github/workflows/pr-notification.yml
  .github/workflows/pr-slack-notify.yml
Labels: fix

#113 feat : 펫 등록하기 페이지
  frontend/src/app/login/page.tsx
  frontend/src/app/pets/register/page.tsx
  frontend/src/shared/components/layout/Header.tsx
  frontend/src/shared/hooks/useAuth.ts
  frontend/src/shared/services/petService.ts
  frontend/src/shared/types/index.ts
Labels: feat

#122 fix: 배포 환경에서 카카오 로그인을 사용하기 위한 하드코딩을 환경변수로 변경
  frontend/src/app/login/page.tsx
Labels: deploy
